// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using NUnit.Framework;

[TestFixture]
public class SUPPORTPAGETest {
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp() {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown() {
        driver.Quit();
    }
    //[Test]
    //public void SUPPORTPAGE()
    //{
    //    driver.Navigate().GoToUrl("https://it.conestogac.on.ca/");
    //    // driver.Manage().Window.Size = new System.Drawing.Size(1600, 1000);
    //    driver.Manage().Window.Maximize();
    //    driver.FindElement(By.LinkText("Support")).Click();
    //    js.ExecuteScript("window.scrollTo(0,500)");
    //    driver.FindElement(By.CssSelector("#apps-tools > div:nth-child(20) > a > span > span:nth-child(2)")).Click();
    //    driver.Close();
    //}
    [Test]
    public void GoogleSearch()
    {
        driver.Navigate().GoToUrl("https://www.google.com/");
        driver.Manage().Window.Maximize();
        IWebElement query = driver.FindElement(By.Name("q"));
        query.SendKeys("conestoga college");
        query.Submit();
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(d => d.Title.ToLower().StartsWith("conestoga college"));
    }
    
}
